### ISSUE TITLE
Optimization Of Wrestler.java

### ISSUE THREAD

**Issue by JamesKillmonger** [murphman29/Murphy-Wrestling-Tournament-Manager#1]
Location: src/DataClasses/Wrestler.java

Lines: 129-158

Deficiency: I suggest instead of using a bunch of if, else and else if statements we can use Switch Statements. 

Reason: Not only does it help the code be much more readable thus making manually following along less a headache for our programmers, but even better it increases performance. "When using a switch statement the compiler knows the constants are the same type and all that needs to be done is comparing the equality of each switch." Using if else statements the compiler does not know such things, thus unnecessary extra work is being done. Although it is not a critical issue because we do not have too many if else statements, we have quite a few. If the programmer respects their program, the program respects them.

Information Sources: https://www.geeksforgeeks.org/switch-vs-else/

**Comment by murphman29** [comment]
James,

I completely agree with your suggestion. I'll be posting an update to Wrestler.java here shortly.

When I first wrote that CompareTo method I didn't expect to have as much criteria to sort by, which is why I went with if-then statements.

Thanks,
Jared M

**Comment by murphman29** [comment]
I have uploaded my patch to the master branch
